(cl:in-package e_car_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CRASHCLEARCMD_VALID-VAL
          CRASHCLEARCMD_VALID
          CRASHCLEAR_CMD-VAL
          CRASHCLEAR_CMD
          EMGCSWHCLEARCMD_VALID-VAL
          EMGCSWHCLEARCMD_VALID
          EMGCSWHCLEAR_CMD-VAL
          EMGCSWHCLEAR_CMD
          CRASHCLR_ROLLCNT-VAL
          CRASHCLR_ROLLCNT
          CRASHCLR_CHECKSUM-VAL
          CRASHCLR_CHECKSUM
))