(cl:in-package e_car_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ADCHASPWRUP_CMD-VAL
          ADCHASPWRUP_CMD
          AD12VMCPWRUP_CMD-VAL
          AD12VMCPWRUP_CMD
          AD12VSC1PWRUP_CMD-VAL
          AD12VSC1PWRUP_CMD
          AD12VSC2PWRUP_CMD-VAL
          AD12VSC2PWRUP_CMD
          AD12VSC3PWRUP_CMD-VAL
          AD12VSC3PWRUP_CMD
          AD12VSC4PWRUP_CMD-VAL
          AD12VSC4PWRUP_CMD
          AD12VSC5PWRUP_CMD-VAL
          AD12VSC5PWRUP_CMD
          AD12VSC6PWRUP_CMD-VAL
          AD12VSC6PWRUP_CMD
          PWRCMD_ROLLCNT-VAL
          PWRCMD_ROLLCNT
          PWRCMD_CHECKSUM-VAL
          PWRCMD_CHECKSUM
))