(cl:in-package e_car_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TOTALTRIPCLEAR_CMD-VAL
          TOTALTRIPCLEAR_CMD
          RMTDRVTRIPCLEAR_CMD-VAL
          RMTDRVTRIPCLEAR_CMD
          AUTODRVTRIPCLEAR_CMD-VAL
          AUTODRVTRIPCLEAR_CMD
          CLDDRVTRIPCLEAR_CMD-VAL
          CLDDRVTRIPCLEAR_CMD
          TRIPCLEAR_ROLLCNT-VAL
          TRIPCLEAR_ROLLCNT
          TRIPCLEAR_CHECKSUM-VAL
          TRIPCLEAR_CHECKSUM
))