(cl:in-package e_car_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAMPCMD_ACTIVE-VAL
          LAMPCMD_ACTIVE
          HEADLAMP_CMD-VAL
          HEADLAMP_CMD
          DBLFLASHLAMP_CMD-VAL
          DBLFLASHLAMP_CMD
          TURNLLAMP_CMD-VAL
          TURNLLAMP_CMD
          TURNRLAMP_CMD-VAL
          TURNRLAMP_CMD
          BACKLAMP_CMD-VAL
          BACKLAMP_CMD
          BUZZER_CMD-VAL
          BUZZER_CMD
          HORN_CMD-VAL
          HORN_CMD
          RUNLAMP_CMD-VAL
          RUNLAMP_CMD
          BRKLAMP_CMD-VAL
          BRKLAMP_CMD
          FOGLAMP_CMD-VAL
          FOGLAMP_CMD
          WIDTHLAMP_CMD-VAL
          WIDTHLAMP_CMD
          LAMPCMD_ROLLCNT-VAL
          LAMPCMD_ROLLCNT
          LAMPCMD_CHECKSUM-VAL
          LAMPCMD_CHECKSUM
))