// Generated by gencpp from file e_car_msgs/ADCU_BrakeCmd.msg
// DO NOT EDIT!


#ifndef E_CAR_MSGS_MESSAGE_ADCU_BRAKECMD_H
#define E_CAR_MSGS_MESSAGE_ADCU_BRAKECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace e_car_msgs
{
template <class ContainerAllocator>
struct ADCU_BrakeCmd_
{
  typedef ADCU_BrakeCmd_<ContainerAllocator> Type;

  ADCU_BrakeCmd_()
    : header()
    , Brk_Active(0)
    , Brk_CtrlMode(0)
    , Brk_TgtPedpos(0.0)
    , Brk_TgtPress(0.0)
    , Brk_TgtAccSpd(0.0)
    , BrkCmd_RollCnt(0)
    , BrkCmd_Checksum(0)  {
    }
  ADCU_BrakeCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Brk_Active(0)
    , Brk_CtrlMode(0)
    , Brk_TgtPedpos(0.0)
    , Brk_TgtPress(0.0)
    , Brk_TgtAccSpd(0.0)
    , BrkCmd_RollCnt(0)
    , BrkCmd_Checksum(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _Brk_Active_type;
  _Brk_Active_type Brk_Active;

   typedef int8_t _Brk_CtrlMode_type;
  _Brk_CtrlMode_type Brk_CtrlMode;

   typedef float _Brk_TgtPedpos_type;
  _Brk_TgtPedpos_type Brk_TgtPedpos;

   typedef float _Brk_TgtPress_type;
  _Brk_TgtPress_type Brk_TgtPress;

   typedef float _Brk_TgtAccSpd_type;
  _Brk_TgtAccSpd_type Brk_TgtAccSpd;

   typedef int32_t _BrkCmd_RollCnt_type;
  _BrkCmd_RollCnt_type BrkCmd_RollCnt;

   typedef int32_t _BrkCmd_Checksum_type;
  _BrkCmd_Checksum_type BrkCmd_Checksum;





  typedef boost::shared_ptr< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ADCU_BrakeCmd_

typedef ::e_car_msgs::ADCU_BrakeCmd_<std::allocator<void> > ADCU_BrakeCmd;

typedef boost::shared_ptr< ::e_car_msgs::ADCU_BrakeCmd > ADCU_BrakeCmdPtr;
typedef boost::shared_ptr< ::e_car_msgs::ADCU_BrakeCmd const> ADCU_BrakeCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Brk_Active == rhs.Brk_Active &&
    lhs.Brk_CtrlMode == rhs.Brk_CtrlMode &&
    lhs.Brk_TgtPedpos == rhs.Brk_TgtPedpos &&
    lhs.Brk_TgtPress == rhs.Brk_TgtPress &&
    lhs.Brk_TgtAccSpd == rhs.Brk_TgtAccSpd &&
    lhs.BrkCmd_RollCnt == rhs.BrkCmd_RollCnt &&
    lhs.BrkCmd_Checksum == rhs.BrkCmd_Checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace e_car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3c2117e1232bca759470cc478a35c8d";
  }

  static const char* value(const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3c2117e1232bca7ULL;
  static const uint64_t static_value2 = 0x59470cc478a35c8dULL;
};

template<class ContainerAllocator>
struct DataType< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e_car_msgs/ADCU_BrakeCmd";
  }

  static const char* value(const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 Brk_Active\n"
"\n"
"int8 Brk_CtrlMode\n"
"\n"
"float32 Brk_TgtPedpos\n"
"\n"
"float32 Brk_TgtPress\n"
"\n"
"float32 Brk_TgtAccSpd\n"
"\n"
"int32 BrkCmd_RollCnt\n"
"\n"
"int32 BrkCmd_Checksum\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Brk_Active);
      stream.next(m.Brk_CtrlMode);
      stream.next(m.Brk_TgtPedpos);
      stream.next(m.Brk_TgtPress);
      stream.next(m.Brk_TgtAccSpd);
      stream.next(m.BrkCmd_RollCnt);
      stream.next(m.BrkCmd_Checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADCU_BrakeCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::e_car_msgs::ADCU_BrakeCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Brk_Active: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Brk_Active);
    s << indent << "Brk_CtrlMode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Brk_CtrlMode);
    s << indent << "Brk_TgtPedpos: ";
    Printer<float>::stream(s, indent + "  ", v.Brk_TgtPedpos);
    s << indent << "Brk_TgtPress: ";
    Printer<float>::stream(s, indent + "  ", v.Brk_TgtPress);
    s << indent << "Brk_TgtAccSpd: ";
    Printer<float>::stream(s, indent + "  ", v.Brk_TgtAccSpd);
    s << indent << "BrkCmd_RollCnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BrkCmd_RollCnt);
    s << indent << "BrkCmd_Checksum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BrkCmd_Checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // E_CAR_MSGS_MESSAGE_ADCU_BRAKECMD_H
