// Generated by gencpp from file e_car_msgs/ADCU_DriveCmd.msg
// DO NOT EDIT!


#ifndef E_CAR_MSGS_MESSAGE_ADCU_DRIVECMD_H
#define E_CAR_MSGS_MESSAGE_ADCU_DRIVECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace e_car_msgs
{
template <class ContainerAllocator>
struct ADCU_DriveCmd_
{
  typedef ADCU_DriveCmd_<ContainerAllocator> Type;

  ADCU_DriveCmd_()
    : header()
    , Drv_Active(0)
    , Drv_CtrlMode(0)
    , Drv_TgtGear(0)
    , Drv_TgtPedpos(0)
    , Drv_TgtVehSpd0(0.0)
    , DrvCmd0_RollCnt(0)
    , DrvCmd0_Checksum(0)  {
    }
  ADCU_DriveCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Drv_Active(0)
    , Drv_CtrlMode(0)
    , Drv_TgtGear(0)
    , Drv_TgtPedpos(0)
    , Drv_TgtVehSpd0(0.0)
    , DrvCmd0_RollCnt(0)
    , DrvCmd0_Checksum(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _Drv_Active_type;
  _Drv_Active_type Drv_Active;

   typedef int8_t _Drv_CtrlMode_type;
  _Drv_CtrlMode_type Drv_CtrlMode;

   typedef int8_t _Drv_TgtGear_type;
  _Drv_TgtGear_type Drv_TgtGear;

   typedef int32_t _Drv_TgtPedpos_type;
  _Drv_TgtPedpos_type Drv_TgtPedpos;

   typedef float _Drv_TgtVehSpd0_type;
  _Drv_TgtVehSpd0_type Drv_TgtVehSpd0;

   typedef int32_t _DrvCmd0_RollCnt_type;
  _DrvCmd0_RollCnt_type DrvCmd0_RollCnt;

   typedef int32_t _DrvCmd0_Checksum_type;
  _DrvCmd0_Checksum_type DrvCmd0_Checksum;





  typedef boost::shared_ptr< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ADCU_DriveCmd_

typedef ::e_car_msgs::ADCU_DriveCmd_<std::allocator<void> > ADCU_DriveCmd;

typedef boost::shared_ptr< ::e_car_msgs::ADCU_DriveCmd > ADCU_DriveCmdPtr;
typedef boost::shared_ptr< ::e_car_msgs::ADCU_DriveCmd const> ADCU_DriveCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Drv_Active == rhs.Drv_Active &&
    lhs.Drv_CtrlMode == rhs.Drv_CtrlMode &&
    lhs.Drv_TgtGear == rhs.Drv_TgtGear &&
    lhs.Drv_TgtPedpos == rhs.Drv_TgtPedpos &&
    lhs.Drv_TgtVehSpd0 == rhs.Drv_TgtVehSpd0 &&
    lhs.DrvCmd0_RollCnt == rhs.DrvCmd0_RollCnt &&
    lhs.DrvCmd0_Checksum == rhs.DrvCmd0_Checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace e_car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6768bd00ea2c2e5ce1f0b7314b783986";
  }

  static const char* value(const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6768bd00ea2c2e5cULL;
  static const uint64_t static_value2 = 0xe1f0b7314b783986ULL;
};

template<class ContainerAllocator>
struct DataType< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e_car_msgs/ADCU_DriveCmd";
  }

  static const char* value(const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 Drv_Active\n"
"\n"
"int8 Drv_CtrlMode\n"
"\n"
"int8 Drv_TgtGear\n"
"\n"
"int32 Drv_TgtPedpos\n"
"\n"
"float32 Drv_TgtVehSpd0\n"
"\n"
"int32 DrvCmd0_RollCnt\n"
"\n"
"int32 DrvCmd0_Checksum\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Drv_Active);
      stream.next(m.Drv_CtrlMode);
      stream.next(m.Drv_TgtGear);
      stream.next(m.Drv_TgtPedpos);
      stream.next(m.Drv_TgtVehSpd0);
      stream.next(m.DrvCmd0_RollCnt);
      stream.next(m.DrvCmd0_Checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADCU_DriveCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::e_car_msgs::ADCU_DriveCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Drv_Active: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Drv_Active);
    s << indent << "Drv_CtrlMode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Drv_CtrlMode);
    s << indent << "Drv_TgtGear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Drv_TgtGear);
    s << indent << "Drv_TgtPedpos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Drv_TgtPedpos);
    s << indent << "Drv_TgtVehSpd0: ";
    Printer<float>::stream(s, indent + "  ", v.Drv_TgtVehSpd0);
    s << indent << "DrvCmd0_RollCnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.DrvCmd0_RollCnt);
    s << indent << "DrvCmd0_Checksum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.DrvCmd0_Checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // E_CAR_MSGS_MESSAGE_ADCU_DRIVECMD_H
