// Generated by gencpp from file e_car_msgs/ADCU_PowerCmd.msg
// DO NOT EDIT!


#ifndef E_CAR_MSGS_MESSAGE_ADCU_POWERCMD_H
#define E_CAR_MSGS_MESSAGE_ADCU_POWERCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace e_car_msgs
{
template <class ContainerAllocator>
struct ADCU_PowerCmd_
{
  typedef ADCU_PowerCmd_<ContainerAllocator> Type;

  ADCU_PowerCmd_()
    : header()
    , ADVehPwrup_Cmd(0)
    , ADChasPwrup_Cmd(0)
    , AD12VMCPwrup_Cmd(0)
    , AD12VRCPwrup_Cmd(0)
    , AD24VMCPwrup_Cmd(0)
    , ADPA12VPwrup_Cmd(0)
    , ADPA24VPwrup_Cmd(0)
    , AD12VSC1Pwrup_Cmd(0)
    , AD12VSC2Pwrup_Cmd(0)
    , AD12VSC3Pwrup_Cmd(0)
    , AD12VSC4Pwrup_Cmd(0)
    , AD12VSC5Pwrup_Cmd(0)
    , AD12VSC6Pwrup_Cmd(0)
    , AD12VMCPwrdownCnfm_Cmd(0)
    , AD12VRCPwrdownCnfm_Cmd(0)
    , AD24VMCPwrdownCnfm_Cmd(0)
    , ADPA12VPwrdownCnfm_Cmd(0)
    , ADPA24VPwrdwnCnfm_Cmd(0)
    , PwrCmd_RollCnt(0)
    , PwrCmd_Checksum(0)  {
    }
  ADCU_PowerCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ADVehPwrup_Cmd(0)
    , ADChasPwrup_Cmd(0)
    , AD12VMCPwrup_Cmd(0)
    , AD12VRCPwrup_Cmd(0)
    , AD24VMCPwrup_Cmd(0)
    , ADPA12VPwrup_Cmd(0)
    , ADPA24VPwrup_Cmd(0)
    , AD12VSC1Pwrup_Cmd(0)
    , AD12VSC2Pwrup_Cmd(0)
    , AD12VSC3Pwrup_Cmd(0)
    , AD12VSC4Pwrup_Cmd(0)
    , AD12VSC5Pwrup_Cmd(0)
    , AD12VSC6Pwrup_Cmd(0)
    , AD12VMCPwrdownCnfm_Cmd(0)
    , AD12VRCPwrdownCnfm_Cmd(0)
    , AD24VMCPwrdownCnfm_Cmd(0)
    , ADPA12VPwrdownCnfm_Cmd(0)
    , ADPA24VPwrdwnCnfm_Cmd(0)
    , PwrCmd_RollCnt(0)
    , PwrCmd_Checksum(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _ADVehPwrup_Cmd_type;
  _ADVehPwrup_Cmd_type ADVehPwrup_Cmd;

   typedef int8_t _ADChasPwrup_Cmd_type;
  _ADChasPwrup_Cmd_type ADChasPwrup_Cmd;

   typedef int8_t _AD12VMCPwrup_Cmd_type;
  _AD12VMCPwrup_Cmd_type AD12VMCPwrup_Cmd;

   typedef int8_t _AD12VRCPwrup_Cmd_type;
  _AD12VRCPwrup_Cmd_type AD12VRCPwrup_Cmd;

   typedef int8_t _AD24VMCPwrup_Cmd_type;
  _AD24VMCPwrup_Cmd_type AD24VMCPwrup_Cmd;

   typedef int8_t _ADPA12VPwrup_Cmd_type;
  _ADPA12VPwrup_Cmd_type ADPA12VPwrup_Cmd;

   typedef int8_t _ADPA24VPwrup_Cmd_type;
  _ADPA24VPwrup_Cmd_type ADPA24VPwrup_Cmd;

   typedef int8_t _AD12VSC1Pwrup_Cmd_type;
  _AD12VSC1Pwrup_Cmd_type AD12VSC1Pwrup_Cmd;

   typedef int8_t _AD12VSC2Pwrup_Cmd_type;
  _AD12VSC2Pwrup_Cmd_type AD12VSC2Pwrup_Cmd;

   typedef int8_t _AD12VSC3Pwrup_Cmd_type;
  _AD12VSC3Pwrup_Cmd_type AD12VSC3Pwrup_Cmd;

   typedef int8_t _AD12VSC4Pwrup_Cmd_type;
  _AD12VSC4Pwrup_Cmd_type AD12VSC4Pwrup_Cmd;

   typedef int8_t _AD12VSC5Pwrup_Cmd_type;
  _AD12VSC5Pwrup_Cmd_type AD12VSC5Pwrup_Cmd;

   typedef int8_t _AD12VSC6Pwrup_Cmd_type;
  _AD12VSC6Pwrup_Cmd_type AD12VSC6Pwrup_Cmd;

   typedef int8_t _AD12VMCPwrdownCnfm_Cmd_type;
  _AD12VMCPwrdownCnfm_Cmd_type AD12VMCPwrdownCnfm_Cmd;

   typedef int8_t _AD12VRCPwrdownCnfm_Cmd_type;
  _AD12VRCPwrdownCnfm_Cmd_type AD12VRCPwrdownCnfm_Cmd;

   typedef int8_t _AD24VMCPwrdownCnfm_Cmd_type;
  _AD24VMCPwrdownCnfm_Cmd_type AD24VMCPwrdownCnfm_Cmd;

   typedef int8_t _ADPA12VPwrdownCnfm_Cmd_type;
  _ADPA12VPwrdownCnfm_Cmd_type ADPA12VPwrdownCnfm_Cmd;

   typedef int8_t _ADPA24VPwrdwnCnfm_Cmd_type;
  _ADPA24VPwrdwnCnfm_Cmd_type ADPA24VPwrdwnCnfm_Cmd;

   typedef int32_t _PwrCmd_RollCnt_type;
  _PwrCmd_RollCnt_type PwrCmd_RollCnt;

   typedef int32_t _PwrCmd_Checksum_type;
  _PwrCmd_Checksum_type PwrCmd_Checksum;





  typedef boost::shared_ptr< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ADCU_PowerCmd_

typedef ::e_car_msgs::ADCU_PowerCmd_<std::allocator<void> > ADCU_PowerCmd;

typedef boost::shared_ptr< ::e_car_msgs::ADCU_PowerCmd > ADCU_PowerCmdPtr;
typedef boost::shared_ptr< ::e_car_msgs::ADCU_PowerCmd const> ADCU_PowerCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ADVehPwrup_Cmd == rhs.ADVehPwrup_Cmd &&
    lhs.ADChasPwrup_Cmd == rhs.ADChasPwrup_Cmd &&
    lhs.AD12VMCPwrup_Cmd == rhs.AD12VMCPwrup_Cmd &&
    lhs.AD12VRCPwrup_Cmd == rhs.AD12VRCPwrup_Cmd &&
    lhs.AD24VMCPwrup_Cmd == rhs.AD24VMCPwrup_Cmd &&
    lhs.ADPA12VPwrup_Cmd == rhs.ADPA12VPwrup_Cmd &&
    lhs.ADPA24VPwrup_Cmd == rhs.ADPA24VPwrup_Cmd &&
    lhs.AD12VSC1Pwrup_Cmd == rhs.AD12VSC1Pwrup_Cmd &&
    lhs.AD12VSC2Pwrup_Cmd == rhs.AD12VSC2Pwrup_Cmd &&
    lhs.AD12VSC3Pwrup_Cmd == rhs.AD12VSC3Pwrup_Cmd &&
    lhs.AD12VSC4Pwrup_Cmd == rhs.AD12VSC4Pwrup_Cmd &&
    lhs.AD12VSC5Pwrup_Cmd == rhs.AD12VSC5Pwrup_Cmd &&
    lhs.AD12VSC6Pwrup_Cmd == rhs.AD12VSC6Pwrup_Cmd &&
    lhs.AD12VMCPwrdownCnfm_Cmd == rhs.AD12VMCPwrdownCnfm_Cmd &&
    lhs.AD12VRCPwrdownCnfm_Cmd == rhs.AD12VRCPwrdownCnfm_Cmd &&
    lhs.AD24VMCPwrdownCnfm_Cmd == rhs.AD24VMCPwrdownCnfm_Cmd &&
    lhs.ADPA12VPwrdownCnfm_Cmd == rhs.ADPA12VPwrdownCnfm_Cmd &&
    lhs.ADPA24VPwrdwnCnfm_Cmd == rhs.ADPA24VPwrdwnCnfm_Cmd &&
    lhs.PwrCmd_RollCnt == rhs.PwrCmd_RollCnt &&
    lhs.PwrCmd_Checksum == rhs.PwrCmd_Checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace e_car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c35626040527e5a2f86622e5735f1b6f";
  }

  static const char* value(const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc35626040527e5a2ULL;
  static const uint64_t static_value2 = 0xf86622e5735f1b6fULL;
};

template<class ContainerAllocator>
struct DataType< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e_car_msgs/ADCU_PowerCmd";
  }

  static const char* value(const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 ADVehPwrup_Cmd\n"
"\n"
"int8 ADChasPwrup_Cmd\n"
"\n"
"int8 AD12VMCPwrup_Cmd\n"
"\n"
"int8 AD12VRCPwrup_Cmd\n"
"\n"
"int8 AD24VMCPwrup_Cmd\n"
"\n"
"int8 ADPA12VPwrup_Cmd\n"
"\n"
"int8 ADPA24VPwrup_Cmd\n"
"\n"
"int8 AD12VSC1Pwrup_Cmd\n"
"\n"
"int8 AD12VSC2Pwrup_Cmd\n"
"\n"
"int8 AD12VSC3Pwrup_Cmd\n"
"\n"
"int8 AD12VSC4Pwrup_Cmd\n"
"\n"
"int8 AD12VSC5Pwrup_Cmd\n"
"\n"
"int8 AD12VSC6Pwrup_Cmd\n"
"\n"
"int8 AD12VMCPwrdownCnfm_Cmd\n"
"\n"
"int8 AD12VRCPwrdownCnfm_Cmd\n"
"\n"
"int8 AD24VMCPwrdownCnfm_Cmd\n"
"\n"
"int8 ADPA12VPwrdownCnfm_Cmd\n"
"\n"
"int8 ADPA24VPwrdwnCnfm_Cmd\n"
"\n"
"int32 PwrCmd_RollCnt\n"
"\n"
"int32 PwrCmd_Checksum\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ADVehPwrup_Cmd);
      stream.next(m.ADChasPwrup_Cmd);
      stream.next(m.AD12VMCPwrup_Cmd);
      stream.next(m.AD12VRCPwrup_Cmd);
      stream.next(m.AD24VMCPwrup_Cmd);
      stream.next(m.ADPA12VPwrup_Cmd);
      stream.next(m.ADPA24VPwrup_Cmd);
      stream.next(m.AD12VSC1Pwrup_Cmd);
      stream.next(m.AD12VSC2Pwrup_Cmd);
      stream.next(m.AD12VSC3Pwrup_Cmd);
      stream.next(m.AD12VSC4Pwrup_Cmd);
      stream.next(m.AD12VSC5Pwrup_Cmd);
      stream.next(m.AD12VSC6Pwrup_Cmd);
      stream.next(m.AD12VMCPwrdownCnfm_Cmd);
      stream.next(m.AD12VRCPwrdownCnfm_Cmd);
      stream.next(m.AD24VMCPwrdownCnfm_Cmd);
      stream.next(m.ADPA12VPwrdownCnfm_Cmd);
      stream.next(m.ADPA24VPwrdwnCnfm_Cmd);
      stream.next(m.PwrCmd_RollCnt);
      stream.next(m.PwrCmd_Checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADCU_PowerCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::e_car_msgs::ADCU_PowerCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ADVehPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ADVehPwrup_Cmd);
    s << indent << "ADChasPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ADChasPwrup_Cmd);
    s << indent << "AD12VMCPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VMCPwrup_Cmd);
    s << indent << "AD12VRCPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VRCPwrup_Cmd);
    s << indent << "AD24VMCPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD24VMCPwrup_Cmd);
    s << indent << "ADPA12VPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ADPA12VPwrup_Cmd);
    s << indent << "ADPA24VPwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ADPA24VPwrup_Cmd);
    s << indent << "AD12VSC1Pwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VSC1Pwrup_Cmd);
    s << indent << "AD12VSC2Pwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VSC2Pwrup_Cmd);
    s << indent << "AD12VSC3Pwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VSC3Pwrup_Cmd);
    s << indent << "AD12VSC4Pwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VSC4Pwrup_Cmd);
    s << indent << "AD12VSC5Pwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VSC5Pwrup_Cmd);
    s << indent << "AD12VSC6Pwrup_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VSC6Pwrup_Cmd);
    s << indent << "AD12VMCPwrdownCnfm_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VMCPwrdownCnfm_Cmd);
    s << indent << "AD12VRCPwrdownCnfm_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD12VRCPwrdownCnfm_Cmd);
    s << indent << "AD24VMCPwrdownCnfm_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.AD24VMCPwrdownCnfm_Cmd);
    s << indent << "ADPA12VPwrdownCnfm_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ADPA12VPwrdownCnfm_Cmd);
    s << indent << "ADPA24VPwrdwnCnfm_Cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ADPA24VPwrdwnCnfm_Cmd);
    s << indent << "PwrCmd_RollCnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.PwrCmd_RollCnt);
    s << indent << "PwrCmd_Checksum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.PwrCmd_Checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // E_CAR_MSGS_MESSAGE_ADCU_POWERCMD_H
