// Generated by gencpp from file e_car_msgs/ADCU_CldDrvCmd.msg
// DO NOT EDIT!


#ifndef E_CAR_MSGS_MESSAGE_ADCU_CLDDRVCMD_H
#define E_CAR_MSGS_MESSAGE_ADCU_CLDDRVCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace e_car_msgs
{
template <class ContainerAllocator>
struct ADCU_CldDrvCmd_
{
  typedef ADCU_CldDrvCmd_<ContainerAllocator> Type;

  ADCU_CldDrvCmd_()
    : header()
    , Cld_CtrlActive(0)
    , Cld_PrkEnable(0)
    , Cld_DriveMode(0)
    , Cld_TgtGear(0)
    , Cld_TgtThrotVal(0.0)
    , Cld_TgtBrkVal(0.0)
    , Cld_TgtStrAngle(0.0)
    , CldDrvCmd_RollCnt(0)
    , CldDrvCmd_Checksum(0)  {
    }
  ADCU_CldDrvCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Cld_CtrlActive(0)
    , Cld_PrkEnable(0)
    , Cld_DriveMode(0)
    , Cld_TgtGear(0)
    , Cld_TgtThrotVal(0.0)
    , Cld_TgtBrkVal(0.0)
    , Cld_TgtStrAngle(0.0)
    , CldDrvCmd_RollCnt(0)
    , CldDrvCmd_Checksum(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _Cld_CtrlActive_type;
  _Cld_CtrlActive_type Cld_CtrlActive;

   typedef int8_t _Cld_PrkEnable_type;
  _Cld_PrkEnable_type Cld_PrkEnable;

   typedef int8_t _Cld_DriveMode_type;
  _Cld_DriveMode_type Cld_DriveMode;

   typedef int32_t _Cld_TgtGear_type;
  _Cld_TgtGear_type Cld_TgtGear;

   typedef float _Cld_TgtThrotVal_type;
  _Cld_TgtThrotVal_type Cld_TgtThrotVal;

   typedef float _Cld_TgtBrkVal_type;
  _Cld_TgtBrkVal_type Cld_TgtBrkVal;

   typedef float _Cld_TgtStrAngle_type;
  _Cld_TgtStrAngle_type Cld_TgtStrAngle;

   typedef int32_t _CldDrvCmd_RollCnt_type;
  _CldDrvCmd_RollCnt_type CldDrvCmd_RollCnt;

   typedef int32_t _CldDrvCmd_Checksum_type;
  _CldDrvCmd_Checksum_type CldDrvCmd_Checksum;





  typedef boost::shared_ptr< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ADCU_CldDrvCmd_

typedef ::e_car_msgs::ADCU_CldDrvCmd_<std::allocator<void> > ADCU_CldDrvCmd;

typedef boost::shared_ptr< ::e_car_msgs::ADCU_CldDrvCmd > ADCU_CldDrvCmdPtr;
typedef boost::shared_ptr< ::e_car_msgs::ADCU_CldDrvCmd const> ADCU_CldDrvCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Cld_CtrlActive == rhs.Cld_CtrlActive &&
    lhs.Cld_PrkEnable == rhs.Cld_PrkEnable &&
    lhs.Cld_DriveMode == rhs.Cld_DriveMode &&
    lhs.Cld_TgtGear == rhs.Cld_TgtGear &&
    lhs.Cld_TgtThrotVal == rhs.Cld_TgtThrotVal &&
    lhs.Cld_TgtBrkVal == rhs.Cld_TgtBrkVal &&
    lhs.Cld_TgtStrAngle == rhs.Cld_TgtStrAngle &&
    lhs.CldDrvCmd_RollCnt == rhs.CldDrvCmd_RollCnt &&
    lhs.CldDrvCmd_Checksum == rhs.CldDrvCmd_Checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator1> & lhs, const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace e_car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03ef622a29189d40a66afa9e28b57a09";
  }

  static const char* value(const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03ef622a29189d40ULL;
  static const uint64_t static_value2 = 0xa66afa9e28b57a09ULL;
};

template<class ContainerAllocator>
struct DataType< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e_car_msgs/ADCU_CldDrvCmd";
  }

  static const char* value(const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 Cld_CtrlActive\n"
"\n"
"int8 Cld_PrkEnable\n"
"\n"
"int8 Cld_DriveMode\n"
"\n"
"int32 Cld_TgtGear\n"
"\n"
"float32 Cld_TgtThrotVal\n"
"\n"
"float32 Cld_TgtBrkVal\n"
"\n"
"float32 Cld_TgtStrAngle\n"
"\n"
"int32 CldDrvCmd_RollCnt\n"
"\n"
"int32 CldDrvCmd_Checksum\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Cld_CtrlActive);
      stream.next(m.Cld_PrkEnable);
      stream.next(m.Cld_DriveMode);
      stream.next(m.Cld_TgtGear);
      stream.next(m.Cld_TgtThrotVal);
      stream.next(m.Cld_TgtBrkVal);
      stream.next(m.Cld_TgtStrAngle);
      stream.next(m.CldDrvCmd_RollCnt);
      stream.next(m.CldDrvCmd_Checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADCU_CldDrvCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::e_car_msgs::ADCU_CldDrvCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Cld_CtrlActive: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Cld_CtrlActive);
    s << indent << "Cld_PrkEnable: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Cld_PrkEnable);
    s << indent << "Cld_DriveMode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Cld_DriveMode);
    s << indent << "Cld_TgtGear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Cld_TgtGear);
    s << indent << "Cld_TgtThrotVal: ";
    Printer<float>::stream(s, indent + "  ", v.Cld_TgtThrotVal);
    s << indent << "Cld_TgtBrkVal: ";
    Printer<float>::stream(s, indent + "  ", v.Cld_TgtBrkVal);
    s << indent << "Cld_TgtStrAngle: ";
    Printer<float>::stream(s, indent + "  ", v.Cld_TgtStrAngle);
    s << indent << "CldDrvCmd_RollCnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.CldDrvCmd_RollCnt);
    s << indent << "CldDrvCmd_Checksum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.CldDrvCmd_Checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // E_CAR_MSGS_MESSAGE_ADCU_CLDDRVCMD_H
