# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from e_car_msgs/ADCU_BodyCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ADCU_BodyCmd(genpy.Message):
  _md5sum = "d293b40475c67e82549c2ea01e9369b9"
  _type = "e_car_msgs/ADCU_BodyCmd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 LampCmd_Active

int8 HeadLamp_Cmd

int8 DblFlashLamp_Cmd

int8 TurnLLamp_Cmd

int8 TurnRLamp_Cmd

int8 BackLamp_Cmd

int8 Buzzer_Cmd

int8 Horn_Cmd

int8 RunLamp_Cmd

int8 BrkLamp_Cmd

int8 FogLamp_Cmd

int8 WidthLamp_Cmd

int32 LampCmd_RollCnt

int32 LampCmd_Checksum
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','LampCmd_Active','HeadLamp_Cmd','DblFlashLamp_Cmd','TurnLLamp_Cmd','TurnRLamp_Cmd','BackLamp_Cmd','Buzzer_Cmd','Horn_Cmd','RunLamp_Cmd','BrkLamp_Cmd','FogLamp_Cmd','WidthLamp_Cmd','LampCmd_RollCnt','LampCmd_Checksum']
  _slot_types = ['std_msgs/Header','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,LampCmd_Active,HeadLamp_Cmd,DblFlashLamp_Cmd,TurnLLamp_Cmd,TurnRLamp_Cmd,BackLamp_Cmd,Buzzer_Cmd,Horn_Cmd,RunLamp_Cmd,BrkLamp_Cmd,FogLamp_Cmd,WidthLamp_Cmd,LampCmd_RollCnt,LampCmd_Checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ADCU_BodyCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.LampCmd_Active is None:
        self.LampCmd_Active = 0
      if self.HeadLamp_Cmd is None:
        self.HeadLamp_Cmd = 0
      if self.DblFlashLamp_Cmd is None:
        self.DblFlashLamp_Cmd = 0
      if self.TurnLLamp_Cmd is None:
        self.TurnLLamp_Cmd = 0
      if self.TurnRLamp_Cmd is None:
        self.TurnRLamp_Cmd = 0
      if self.BackLamp_Cmd is None:
        self.BackLamp_Cmd = 0
      if self.Buzzer_Cmd is None:
        self.Buzzer_Cmd = 0
      if self.Horn_Cmd is None:
        self.Horn_Cmd = 0
      if self.RunLamp_Cmd is None:
        self.RunLamp_Cmd = 0
      if self.BrkLamp_Cmd is None:
        self.BrkLamp_Cmd = 0
      if self.FogLamp_Cmd is None:
        self.FogLamp_Cmd = 0
      if self.WidthLamp_Cmd is None:
        self.WidthLamp_Cmd = 0
      if self.LampCmd_RollCnt is None:
        self.LampCmd_RollCnt = 0
      if self.LampCmd_Checksum is None:
        self.LampCmd_Checksum = 0
    else:
      self.header = std_msgs.msg.Header()
      self.LampCmd_Active = 0
      self.HeadLamp_Cmd = 0
      self.DblFlashLamp_Cmd = 0
      self.TurnLLamp_Cmd = 0
      self.TurnRLamp_Cmd = 0
      self.BackLamp_Cmd = 0
      self.Buzzer_Cmd = 0
      self.Horn_Cmd = 0
      self.RunLamp_Cmd = 0
      self.BrkLamp_Cmd = 0
      self.FogLamp_Cmd = 0
      self.WidthLamp_Cmd = 0
      self.LampCmd_RollCnt = 0
      self.LampCmd_Checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12b2i().pack(_x.LampCmd_Active, _x.HeadLamp_Cmd, _x.DblFlashLamp_Cmd, _x.TurnLLamp_Cmd, _x.TurnRLamp_Cmd, _x.BackLamp_Cmd, _x.Buzzer_Cmd, _x.Horn_Cmd, _x.RunLamp_Cmd, _x.BrkLamp_Cmd, _x.FogLamp_Cmd, _x.WidthLamp_Cmd, _x.LampCmd_RollCnt, _x.LampCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.LampCmd_Active, _x.HeadLamp_Cmd, _x.DblFlashLamp_Cmd, _x.TurnLLamp_Cmd, _x.TurnRLamp_Cmd, _x.BackLamp_Cmd, _x.Buzzer_Cmd, _x.Horn_Cmd, _x.RunLamp_Cmd, _x.BrkLamp_Cmd, _x.FogLamp_Cmd, _x.WidthLamp_Cmd, _x.LampCmd_RollCnt, _x.LampCmd_Checksum,) = _get_struct_12b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12b2i().pack(_x.LampCmd_Active, _x.HeadLamp_Cmd, _x.DblFlashLamp_Cmd, _x.TurnLLamp_Cmd, _x.TurnRLamp_Cmd, _x.BackLamp_Cmd, _x.Buzzer_Cmd, _x.Horn_Cmd, _x.RunLamp_Cmd, _x.BrkLamp_Cmd, _x.FogLamp_Cmd, _x.WidthLamp_Cmd, _x.LampCmd_RollCnt, _x.LampCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.LampCmd_Active, _x.HeadLamp_Cmd, _x.DblFlashLamp_Cmd, _x.TurnLLamp_Cmd, _x.TurnRLamp_Cmd, _x.BackLamp_Cmd, _x.Buzzer_Cmd, _x.Horn_Cmd, _x.RunLamp_Cmd, _x.BrkLamp_Cmd, _x.FogLamp_Cmd, _x.WidthLamp_Cmd, _x.LampCmd_RollCnt, _x.LampCmd_Checksum,) = _get_struct_12b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12b2i = None
def _get_struct_12b2i():
    global _struct_12b2i
    if _struct_12b2i is None:
        _struct_12b2i = struct.Struct("<12b2i")
    return _struct_12b2i
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
