# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from e_car_msgs/ADCU_SteerCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ADCU_SteerCmd(genpy.Message):
  _md5sum = "c28ae07fba8b70da0e80a1960035feb5"
  _type = "e_car_msgs/ADCU_SteerCmd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 Str_Active

int8 Str_CtrlMode

float32 Str_TgtAngle

float32 Str_TgtAngleSpd

int32 StrCmd_RollCnt

int32 StrCmd_Checksum
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','Str_Active','Str_CtrlMode','Str_TgtAngle','Str_TgtAngleSpd','StrCmd_RollCnt','StrCmd_Checksum']
  _slot_types = ['std_msgs/Header','int8','int8','float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Str_Active,Str_CtrlMode,Str_TgtAngle,Str_TgtAngleSpd,StrCmd_RollCnt,StrCmd_Checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ADCU_SteerCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Str_Active is None:
        self.Str_Active = 0
      if self.Str_CtrlMode is None:
        self.Str_CtrlMode = 0
      if self.Str_TgtAngle is None:
        self.Str_TgtAngle = 0.
      if self.Str_TgtAngleSpd is None:
        self.Str_TgtAngleSpd = 0.
      if self.StrCmd_RollCnt is None:
        self.StrCmd_RollCnt = 0
      if self.StrCmd_Checksum is None:
        self.StrCmd_Checksum = 0
    else:
      self.header = std_msgs.msg.Header()
      self.Str_Active = 0
      self.Str_CtrlMode = 0
      self.Str_TgtAngle = 0.
      self.Str_TgtAngleSpd = 0.
      self.StrCmd_RollCnt = 0
      self.StrCmd_Checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2b2f2i().pack(_x.Str_Active, _x.Str_CtrlMode, _x.Str_TgtAngle, _x.Str_TgtAngleSpd, _x.StrCmd_RollCnt, _x.StrCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.Str_Active, _x.Str_CtrlMode, _x.Str_TgtAngle, _x.Str_TgtAngleSpd, _x.StrCmd_RollCnt, _x.StrCmd_Checksum,) = _get_struct_2b2f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2b2f2i().pack(_x.Str_Active, _x.Str_CtrlMode, _x.Str_TgtAngle, _x.Str_TgtAngleSpd, _x.StrCmd_RollCnt, _x.StrCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.Str_Active, _x.Str_CtrlMode, _x.Str_TgtAngle, _x.Str_TgtAngleSpd, _x.StrCmd_RollCnt, _x.StrCmd_Checksum,) = _get_struct_2b2f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b2f2i = None
def _get_struct_2b2f2i():
    global _struct_2b2f2i
    if _struct_2b2f2i is None:
        _struct_2b2f2i = struct.Struct("<2b2f2i")
    return _struct_2b2f2i
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
