# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from e_car_msgs/ADCU_CldPowerCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ADCU_CldPowerCmd(genpy.Message):
  _md5sum = "712914972d7a36597399d67071cb4425"
  _type = "e_car_msgs/ADCU_CldPowerCmd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 CldVehPwrup_Cmd

int8 CldChasPwrup_Cmd

int8 Cld12VMCPwrup_Cmd

int8 Cld12VRCPwrup_Cmd

int8 Cld24VMCPwrup_Cmd

int8 CldPA12VPwrup_Cmd

int8 CldPA24VPwrup_Cmd

int8 Cld12VSC1Pwrup_Cmd

int8 Cld12VSC2Pwrup_Cmd

int8 Cld12VSC3Pwrup_Cmd

int8 Cld12VSC4Pwrup_Cmd

int8 Cld12VSC5Pwrup_Cmd

int8 Cld12VSC6Pwrup_Cmd

int8 Cld12VMCPwrdownCnfm_Cmd

int8 Cld12VRCPwrdownCnfm_Cmd

int8 Cld24VMCPwrdownCnfm_Cmd

int8 CldPA12VPwrdownCnfm_Cmd

int8 CldPA24VPwrdownCnfm_Cmd

int32 CldPwrCmd_RollCnt

int32 CldPwrCmd_Checksum
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','CldVehPwrup_Cmd','CldChasPwrup_Cmd','Cld12VMCPwrup_Cmd','Cld12VRCPwrup_Cmd','Cld24VMCPwrup_Cmd','CldPA12VPwrup_Cmd','CldPA24VPwrup_Cmd','Cld12VSC1Pwrup_Cmd','Cld12VSC2Pwrup_Cmd','Cld12VSC3Pwrup_Cmd','Cld12VSC4Pwrup_Cmd','Cld12VSC5Pwrup_Cmd','Cld12VSC6Pwrup_Cmd','Cld12VMCPwrdownCnfm_Cmd','Cld12VRCPwrdownCnfm_Cmd','Cld24VMCPwrdownCnfm_Cmd','CldPA12VPwrdownCnfm_Cmd','CldPA24VPwrdownCnfm_Cmd','CldPwrCmd_RollCnt','CldPwrCmd_Checksum']
  _slot_types = ['std_msgs/Header','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,CldVehPwrup_Cmd,CldChasPwrup_Cmd,Cld12VMCPwrup_Cmd,Cld12VRCPwrup_Cmd,Cld24VMCPwrup_Cmd,CldPA12VPwrup_Cmd,CldPA24VPwrup_Cmd,Cld12VSC1Pwrup_Cmd,Cld12VSC2Pwrup_Cmd,Cld12VSC3Pwrup_Cmd,Cld12VSC4Pwrup_Cmd,Cld12VSC5Pwrup_Cmd,Cld12VSC6Pwrup_Cmd,Cld12VMCPwrdownCnfm_Cmd,Cld12VRCPwrdownCnfm_Cmd,Cld24VMCPwrdownCnfm_Cmd,CldPA12VPwrdownCnfm_Cmd,CldPA24VPwrdownCnfm_Cmd,CldPwrCmd_RollCnt,CldPwrCmd_Checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ADCU_CldPowerCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.CldVehPwrup_Cmd is None:
        self.CldVehPwrup_Cmd = 0
      if self.CldChasPwrup_Cmd is None:
        self.CldChasPwrup_Cmd = 0
      if self.Cld12VMCPwrup_Cmd is None:
        self.Cld12VMCPwrup_Cmd = 0
      if self.Cld12VRCPwrup_Cmd is None:
        self.Cld12VRCPwrup_Cmd = 0
      if self.Cld24VMCPwrup_Cmd is None:
        self.Cld24VMCPwrup_Cmd = 0
      if self.CldPA12VPwrup_Cmd is None:
        self.CldPA12VPwrup_Cmd = 0
      if self.CldPA24VPwrup_Cmd is None:
        self.CldPA24VPwrup_Cmd = 0
      if self.Cld12VSC1Pwrup_Cmd is None:
        self.Cld12VSC1Pwrup_Cmd = 0
      if self.Cld12VSC2Pwrup_Cmd is None:
        self.Cld12VSC2Pwrup_Cmd = 0
      if self.Cld12VSC3Pwrup_Cmd is None:
        self.Cld12VSC3Pwrup_Cmd = 0
      if self.Cld12VSC4Pwrup_Cmd is None:
        self.Cld12VSC4Pwrup_Cmd = 0
      if self.Cld12VSC5Pwrup_Cmd is None:
        self.Cld12VSC5Pwrup_Cmd = 0
      if self.Cld12VSC6Pwrup_Cmd is None:
        self.Cld12VSC6Pwrup_Cmd = 0
      if self.Cld12VMCPwrdownCnfm_Cmd is None:
        self.Cld12VMCPwrdownCnfm_Cmd = 0
      if self.Cld12VRCPwrdownCnfm_Cmd is None:
        self.Cld12VRCPwrdownCnfm_Cmd = 0
      if self.Cld24VMCPwrdownCnfm_Cmd is None:
        self.Cld24VMCPwrdownCnfm_Cmd = 0
      if self.CldPA12VPwrdownCnfm_Cmd is None:
        self.CldPA12VPwrdownCnfm_Cmd = 0
      if self.CldPA24VPwrdownCnfm_Cmd is None:
        self.CldPA24VPwrdownCnfm_Cmd = 0
      if self.CldPwrCmd_RollCnt is None:
        self.CldPwrCmd_RollCnt = 0
      if self.CldPwrCmd_Checksum is None:
        self.CldPwrCmd_Checksum = 0
    else:
      self.header = std_msgs.msg.Header()
      self.CldVehPwrup_Cmd = 0
      self.CldChasPwrup_Cmd = 0
      self.Cld12VMCPwrup_Cmd = 0
      self.Cld12VRCPwrup_Cmd = 0
      self.Cld24VMCPwrup_Cmd = 0
      self.CldPA12VPwrup_Cmd = 0
      self.CldPA24VPwrup_Cmd = 0
      self.Cld12VSC1Pwrup_Cmd = 0
      self.Cld12VSC2Pwrup_Cmd = 0
      self.Cld12VSC3Pwrup_Cmd = 0
      self.Cld12VSC4Pwrup_Cmd = 0
      self.Cld12VSC5Pwrup_Cmd = 0
      self.Cld12VSC6Pwrup_Cmd = 0
      self.Cld12VMCPwrdownCnfm_Cmd = 0
      self.Cld12VRCPwrdownCnfm_Cmd = 0
      self.Cld24VMCPwrdownCnfm_Cmd = 0
      self.CldPA12VPwrdownCnfm_Cmd = 0
      self.CldPA24VPwrdownCnfm_Cmd = 0
      self.CldPwrCmd_RollCnt = 0
      self.CldPwrCmd_Checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18b2i().pack(_x.CldVehPwrup_Cmd, _x.CldChasPwrup_Cmd, _x.Cld12VMCPwrup_Cmd, _x.Cld12VRCPwrup_Cmd, _x.Cld24VMCPwrup_Cmd, _x.CldPA12VPwrup_Cmd, _x.CldPA24VPwrup_Cmd, _x.Cld12VSC1Pwrup_Cmd, _x.Cld12VSC2Pwrup_Cmd, _x.Cld12VSC3Pwrup_Cmd, _x.Cld12VSC4Pwrup_Cmd, _x.Cld12VSC5Pwrup_Cmd, _x.Cld12VSC6Pwrup_Cmd, _x.Cld12VMCPwrdownCnfm_Cmd, _x.Cld12VRCPwrdownCnfm_Cmd, _x.Cld24VMCPwrdownCnfm_Cmd, _x.CldPA12VPwrdownCnfm_Cmd, _x.CldPA24VPwrdownCnfm_Cmd, _x.CldPwrCmd_RollCnt, _x.CldPwrCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.CldVehPwrup_Cmd, _x.CldChasPwrup_Cmd, _x.Cld12VMCPwrup_Cmd, _x.Cld12VRCPwrup_Cmd, _x.Cld24VMCPwrup_Cmd, _x.CldPA12VPwrup_Cmd, _x.CldPA24VPwrup_Cmd, _x.Cld12VSC1Pwrup_Cmd, _x.Cld12VSC2Pwrup_Cmd, _x.Cld12VSC3Pwrup_Cmd, _x.Cld12VSC4Pwrup_Cmd, _x.Cld12VSC5Pwrup_Cmd, _x.Cld12VSC6Pwrup_Cmd, _x.Cld12VMCPwrdownCnfm_Cmd, _x.Cld12VRCPwrdownCnfm_Cmd, _x.Cld24VMCPwrdownCnfm_Cmd, _x.CldPA12VPwrdownCnfm_Cmd, _x.CldPA24VPwrdownCnfm_Cmd, _x.CldPwrCmd_RollCnt, _x.CldPwrCmd_Checksum,) = _get_struct_18b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18b2i().pack(_x.CldVehPwrup_Cmd, _x.CldChasPwrup_Cmd, _x.Cld12VMCPwrup_Cmd, _x.Cld12VRCPwrup_Cmd, _x.Cld24VMCPwrup_Cmd, _x.CldPA12VPwrup_Cmd, _x.CldPA24VPwrup_Cmd, _x.Cld12VSC1Pwrup_Cmd, _x.Cld12VSC2Pwrup_Cmd, _x.Cld12VSC3Pwrup_Cmd, _x.Cld12VSC4Pwrup_Cmd, _x.Cld12VSC5Pwrup_Cmd, _x.Cld12VSC6Pwrup_Cmd, _x.Cld12VMCPwrdownCnfm_Cmd, _x.Cld12VRCPwrdownCnfm_Cmd, _x.Cld24VMCPwrdownCnfm_Cmd, _x.CldPA12VPwrdownCnfm_Cmd, _x.CldPA24VPwrdownCnfm_Cmd, _x.CldPwrCmd_RollCnt, _x.CldPwrCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.CldVehPwrup_Cmd, _x.CldChasPwrup_Cmd, _x.Cld12VMCPwrup_Cmd, _x.Cld12VRCPwrup_Cmd, _x.Cld24VMCPwrup_Cmd, _x.CldPA12VPwrup_Cmd, _x.CldPA24VPwrup_Cmd, _x.Cld12VSC1Pwrup_Cmd, _x.Cld12VSC2Pwrup_Cmd, _x.Cld12VSC3Pwrup_Cmd, _x.Cld12VSC4Pwrup_Cmd, _x.Cld12VSC5Pwrup_Cmd, _x.Cld12VSC6Pwrup_Cmd, _x.Cld12VMCPwrdownCnfm_Cmd, _x.Cld12VRCPwrdownCnfm_Cmd, _x.Cld24VMCPwrdownCnfm_Cmd, _x.CldPA12VPwrdownCnfm_Cmd, _x.CldPA24VPwrdownCnfm_Cmd, _x.CldPwrCmd_RollCnt, _x.CldPwrCmd_Checksum,) = _get_struct_18b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18b2i = None
def _get_struct_18b2i():
    global _struct_18b2i
    if _struct_18b2i is None:
        _struct_18b2i = struct.Struct("<18b2i")
    return _struct_18b2i
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
