# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from e_car_msgs/ADCU_CldBodyCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ADCU_CldBodyCmd(genpy.Message):
  _md5sum = "e996fa29fe9d34f1678bf393df7a1655"
  _type = "e_car_msgs/ADCU_CldBodyCmd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 Cld_WidthLamp_Cmd

int8 Cld_BrkLamp_Cmd

int8 Cld_FogLamp_Cmd

int8 Cld_HeadLamp_Cmd

int8 Cld_DblFlashLamp_Cmd

int8 Cld_TurnLLamp_Cmd

int8 Cld_TurnRLamp_Cmd

int8 Cld_BackLamp_Cmd

int8 Cld_Buzzer_Cmd

int8 Cld_Horn_Cmd

int8 Cld_RunLamp_Cmd

int32 CldBodyCmd_RollCnt

int32 CldBodyCmd_Checksum
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','Cld_WidthLamp_Cmd','Cld_BrkLamp_Cmd','Cld_FogLamp_Cmd','Cld_HeadLamp_Cmd','Cld_DblFlashLamp_Cmd','Cld_TurnLLamp_Cmd','Cld_TurnRLamp_Cmd','Cld_BackLamp_Cmd','Cld_Buzzer_Cmd','Cld_Horn_Cmd','Cld_RunLamp_Cmd','CldBodyCmd_RollCnt','CldBodyCmd_Checksum']
  _slot_types = ['std_msgs/Header','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Cld_WidthLamp_Cmd,Cld_BrkLamp_Cmd,Cld_FogLamp_Cmd,Cld_HeadLamp_Cmd,Cld_DblFlashLamp_Cmd,Cld_TurnLLamp_Cmd,Cld_TurnRLamp_Cmd,Cld_BackLamp_Cmd,Cld_Buzzer_Cmd,Cld_Horn_Cmd,Cld_RunLamp_Cmd,CldBodyCmd_RollCnt,CldBodyCmd_Checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ADCU_CldBodyCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Cld_WidthLamp_Cmd is None:
        self.Cld_WidthLamp_Cmd = 0
      if self.Cld_BrkLamp_Cmd is None:
        self.Cld_BrkLamp_Cmd = 0
      if self.Cld_FogLamp_Cmd is None:
        self.Cld_FogLamp_Cmd = 0
      if self.Cld_HeadLamp_Cmd is None:
        self.Cld_HeadLamp_Cmd = 0
      if self.Cld_DblFlashLamp_Cmd is None:
        self.Cld_DblFlashLamp_Cmd = 0
      if self.Cld_TurnLLamp_Cmd is None:
        self.Cld_TurnLLamp_Cmd = 0
      if self.Cld_TurnRLamp_Cmd is None:
        self.Cld_TurnRLamp_Cmd = 0
      if self.Cld_BackLamp_Cmd is None:
        self.Cld_BackLamp_Cmd = 0
      if self.Cld_Buzzer_Cmd is None:
        self.Cld_Buzzer_Cmd = 0
      if self.Cld_Horn_Cmd is None:
        self.Cld_Horn_Cmd = 0
      if self.Cld_RunLamp_Cmd is None:
        self.Cld_RunLamp_Cmd = 0
      if self.CldBodyCmd_RollCnt is None:
        self.CldBodyCmd_RollCnt = 0
      if self.CldBodyCmd_Checksum is None:
        self.CldBodyCmd_Checksum = 0
    else:
      self.header = std_msgs.msg.Header()
      self.Cld_WidthLamp_Cmd = 0
      self.Cld_BrkLamp_Cmd = 0
      self.Cld_FogLamp_Cmd = 0
      self.Cld_HeadLamp_Cmd = 0
      self.Cld_DblFlashLamp_Cmd = 0
      self.Cld_TurnLLamp_Cmd = 0
      self.Cld_TurnRLamp_Cmd = 0
      self.Cld_BackLamp_Cmd = 0
      self.Cld_Buzzer_Cmd = 0
      self.Cld_Horn_Cmd = 0
      self.Cld_RunLamp_Cmd = 0
      self.CldBodyCmd_RollCnt = 0
      self.CldBodyCmd_Checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11b2i().pack(_x.Cld_WidthLamp_Cmd, _x.Cld_BrkLamp_Cmd, _x.Cld_FogLamp_Cmd, _x.Cld_HeadLamp_Cmd, _x.Cld_DblFlashLamp_Cmd, _x.Cld_TurnLLamp_Cmd, _x.Cld_TurnRLamp_Cmd, _x.Cld_BackLamp_Cmd, _x.Cld_Buzzer_Cmd, _x.Cld_Horn_Cmd, _x.Cld_RunLamp_Cmd, _x.CldBodyCmd_RollCnt, _x.CldBodyCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.Cld_WidthLamp_Cmd, _x.Cld_BrkLamp_Cmd, _x.Cld_FogLamp_Cmd, _x.Cld_HeadLamp_Cmd, _x.Cld_DblFlashLamp_Cmd, _x.Cld_TurnLLamp_Cmd, _x.Cld_TurnRLamp_Cmd, _x.Cld_BackLamp_Cmd, _x.Cld_Buzzer_Cmd, _x.Cld_Horn_Cmd, _x.Cld_RunLamp_Cmd, _x.CldBodyCmd_RollCnt, _x.CldBodyCmd_Checksum,) = _get_struct_11b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11b2i().pack(_x.Cld_WidthLamp_Cmd, _x.Cld_BrkLamp_Cmd, _x.Cld_FogLamp_Cmd, _x.Cld_HeadLamp_Cmd, _x.Cld_DblFlashLamp_Cmd, _x.Cld_TurnLLamp_Cmd, _x.Cld_TurnRLamp_Cmd, _x.Cld_BackLamp_Cmd, _x.Cld_Buzzer_Cmd, _x.Cld_Horn_Cmd, _x.Cld_RunLamp_Cmd, _x.CldBodyCmd_RollCnt, _x.CldBodyCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.Cld_WidthLamp_Cmd, _x.Cld_BrkLamp_Cmd, _x.Cld_FogLamp_Cmd, _x.Cld_HeadLamp_Cmd, _x.Cld_DblFlashLamp_Cmd, _x.Cld_TurnLLamp_Cmd, _x.Cld_TurnRLamp_Cmd, _x.Cld_BackLamp_Cmd, _x.Cld_Buzzer_Cmd, _x.Cld_Horn_Cmd, _x.Cld_RunLamp_Cmd, _x.CldBodyCmd_RollCnt, _x.CldBodyCmd_Checksum,) = _get_struct_11b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11b2i = None
def _get_struct_11b2i():
    global _struct_11b2i
    if _struct_11b2i is None:
        _struct_11b2i = struct.Struct("<11b2i")
    return _struct_11b2i
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
