# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from e_car_msgs/ADCU_SweepCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ADCU_SweepCmd(genpy.Message):
  _md5sum = "9fc2cfb79831693da7794ecbd5abc3cc"
  _type = "e_car_msgs/ADCU_SweepCmd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 Tgt_SweepMode

int8 Sweep_Cmd

int8 ShakeDust_Cmd

int8 GbgDump_Cmd

int8 FtFenderCtrl_Cmd

int8 SweepEStop_Cmd

int8 BrushWtrValFbd_Cmd

int32 SweepCmd_RollCnt

int32 SweepCmd_Checksum
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','Tgt_SweepMode','Sweep_Cmd','ShakeDust_Cmd','GbgDump_Cmd','FtFenderCtrl_Cmd','SweepEStop_Cmd','BrushWtrValFbd_Cmd','SweepCmd_RollCnt','SweepCmd_Checksum']
  _slot_types = ['std_msgs/Header','int8','int8','int8','int8','int8','int8','int8','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Tgt_SweepMode,Sweep_Cmd,ShakeDust_Cmd,GbgDump_Cmd,FtFenderCtrl_Cmd,SweepEStop_Cmd,BrushWtrValFbd_Cmd,SweepCmd_RollCnt,SweepCmd_Checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ADCU_SweepCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Tgt_SweepMode is None:
        self.Tgt_SweepMode = 0
      if self.Sweep_Cmd is None:
        self.Sweep_Cmd = 0
      if self.ShakeDust_Cmd is None:
        self.ShakeDust_Cmd = 0
      if self.GbgDump_Cmd is None:
        self.GbgDump_Cmd = 0
      if self.FtFenderCtrl_Cmd is None:
        self.FtFenderCtrl_Cmd = 0
      if self.SweepEStop_Cmd is None:
        self.SweepEStop_Cmd = 0
      if self.BrushWtrValFbd_Cmd is None:
        self.BrushWtrValFbd_Cmd = 0
      if self.SweepCmd_RollCnt is None:
        self.SweepCmd_RollCnt = 0
      if self.SweepCmd_Checksum is None:
        self.SweepCmd_Checksum = 0
    else:
      self.header = std_msgs.msg.Header()
      self.Tgt_SweepMode = 0
      self.Sweep_Cmd = 0
      self.ShakeDust_Cmd = 0
      self.GbgDump_Cmd = 0
      self.FtFenderCtrl_Cmd = 0
      self.SweepEStop_Cmd = 0
      self.BrushWtrValFbd_Cmd = 0
      self.SweepCmd_RollCnt = 0
      self.SweepCmd_Checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7b2i().pack(_x.Tgt_SweepMode, _x.Sweep_Cmd, _x.ShakeDust_Cmd, _x.GbgDump_Cmd, _x.FtFenderCtrl_Cmd, _x.SweepEStop_Cmd, _x.BrushWtrValFbd_Cmd, _x.SweepCmd_RollCnt, _x.SweepCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.Tgt_SweepMode, _x.Sweep_Cmd, _x.ShakeDust_Cmd, _x.GbgDump_Cmd, _x.FtFenderCtrl_Cmd, _x.SweepEStop_Cmd, _x.BrushWtrValFbd_Cmd, _x.SweepCmd_RollCnt, _x.SweepCmd_Checksum,) = _get_struct_7b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7b2i().pack(_x.Tgt_SweepMode, _x.Sweep_Cmd, _x.ShakeDust_Cmd, _x.GbgDump_Cmd, _x.FtFenderCtrl_Cmd, _x.SweepEStop_Cmd, _x.BrushWtrValFbd_Cmd, _x.SweepCmd_RollCnt, _x.SweepCmd_Checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.Tgt_SweepMode, _x.Sweep_Cmd, _x.ShakeDust_Cmd, _x.GbgDump_Cmd, _x.FtFenderCtrl_Cmd, _x.SweepEStop_Cmd, _x.BrushWtrValFbd_Cmd, _x.SweepCmd_RollCnt, _x.SweepCmd_Checksum,) = _get_struct_7b2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7b2i = None
def _get_struct_7b2i():
    global _struct_7b2i
    if _struct_7b2i is None:
        _struct_7b2i = struct.Struct("<7b2i")
    return _struct_7b2i
