Header header

int8 ADVehPwrup_Cmd

int8 ADChasPwrup_Cmd

int8 AD12VMCPwrup_Cmd

int8 AD12VRCPwrup_Cmd

int8 AD24VMCPwrup_Cmd

int8 ADPA12VPwrup_Cmd

int8 ADPA24VPwrup_Cmd

int8 AD12VSC1Pwrup_Cmd

int8 AD12VSC2Pwrup_Cmd

int8 AD12VSC3Pwrup_Cmd

int8 AD12VSC4Pwrup_Cmd

int8 AD12VSC5Pwrup_Cmd

int8 AD12VSC6Pwrup_Cmd

int8 AD12VMCPwrdownCnfm_Cmd

int8 AD12VRCPwrdownCnfm_Cmd

int8 AD24VMCPwrdownCnfm_Cmd

int8 ADPA12VPwrdownCnfm_Cmd

int8 ADPA24VPwrdwnCnfm_Cmd

int32 PwrCmd_RollCnt

int32 PwrCmd_Checksum