Header header

int8 CldVehPwrup_Cmd

int8 CldChasPwrup_Cmd

int8 Cld12VMCPwrup_Cmd

int8 Cld12VRCPwrup_Cmd

int8 Cld24VMCPwrup_Cmd

int8 CldPA12VPwrup_Cmd

int8 CldPA24VPwrup_Cmd

int8 Cld12VSC1Pwrup_Cmd

int8 Cld12VSC2Pwrup_Cmd

int8 Cld12VSC3Pwrup_Cmd

int8 Cld12VSC4Pwrup_Cmd

int8 Cld12VSC5Pwrup_Cmd

int8 Cld12VSC6Pwrup_Cmd

int8 Cld12VMCPwrdownCnfm_Cmd

int8 Cld12VRCPwrdownCnfm_Cmd

int8 Cld24VMCPwrdownCnfm_Cmd

int8 CldPA12VPwrdownCnfm_Cmd

int8 CldPA24VPwrdownCnfm_Cmd

int32 CldPwrCmd_RollCnt

int32 CldPwrCmd_Checksum