Header header
#车辆工作模式,0-Standby,1-Inetrrupt,2-Remote,3-Automatic，4-Emergency，5-Cloud,6-Reserved
int8 CDCU_Veh_RunMode
#整车故障等级：0-Normal,1-Level1,2-Level2,3-Level3
int8 CDCU_Veh_ErrLevel
# 
bool CDCU_FtCrash_St
#
bool CDCU_RrCrash_St

bool CDCU_VehEmgcySwh_St

bool CDCU_LvBat_LowVolt

bool CDCU_Bat_LowSOC

int8 CDCU_BMS_ErrLevel


int8 CDCU_MCU_ErrLevel

int8 CDCU_EHB_ErrLevel

int8 CDCU_EPS_ErrLevel

int8 CDCU_EPB_ErrLevel

int8 CDCU_SIU_ErrLevel

int8 CDCU_PDU_ErrLevel

int8 CDCU_CBCU_ErrLevel

int8 CDCU_TirePresrAlarm_St

int8 CDCU_CANBusOff_St

int8 CDCU_Veh_ErrCode

