Header header

#声光系统工作模式,0-Standby,1-Inetrrupt,2-Remote,3-Automatic，4-Emergency
int8 CDCU_AcostOptic_WorkMode

#前大灯开启状态，0-false,1-true
int8 CDCU_HeadLamp_St

#双闪开启状态，0-false,1-true
int8 CDCU_DblFlashLamp_st

#左传灯开启状态，0-false,1-true
int8 CDCU_TurnLLamp_st


#右转灯开启状态，0-false,1-true
int8 CDCU_TurnRLamp_st

#倒车灯开启状态，0-false,1-true
int8 CDCU_BackLamp_st

#警示风鸣器开启状态，0-false,1-true
int8 CDCU_Buzzer_st

#喇叭开启状态，0-false,1-true
int8 CDCU_Horn_st

#日行灯开启状态，0-false,1-true
int8 CDCU_RunLamp_st

#制动灯状态，0-false,1-true
int8 CDCU_BrkLamp_st

#雾灯状态，0-false,1-true
int8 CDCU_FogLamp_st

#示阔灯开启状态，0-false,1-true
int8 CDCU_WidthLamp_st