Header header
#当前清扫模式
int32 cdcu_sweep_mode
#清扫系统工作状态
int32 cdcu_sweep_sys_st
# 清扫系统急停状态
int32 cdcu_sweep_Estop_st
#震尘状态 
int32 cdcu_shake_dust_st
#垃圾仓位置状态
int32 cdcu_dstb_pos_st
#前边刷伸缩状态
int32 cdcu_FtBrushStretch_St
#前边刷升降状态
int32 CDCU_FtBrushDrop_St
#后边刷升降状态
int32 CDCU_RrBrushDrop_St
#主刷升降状态
int32 CDCU_MainBrush_St
#前边刷电机状态
int32 CDCU_FtBrushMtr_St
#后边刷电机状态
int32 CDCU_RrBrushMtr_St
#主刷电机状态
int32 CDCU_MainBrushMtr_St
#离心风机状态
int32 CDCU_CtfgFan_St
#主刷前挡板开关状态
int32 CDCU_FtFender_St
#边刷喷水状态
int32 CDCU_BrushWtrVal_St
#剩余水量
int32 CDCU_Remain_Water

